language: java
jdk:
- oraclejdk8

script: "mvn deploy --settings settings.xml"
env:
  global:
  - secure: "gUye1p5pNyd5zRsBb21yLgS44lZeZIIwf6tSYRtInaLliYMh5SjI5oL1jggu6WzLJ0l1Qiue17bfiHe8lnGXlYIgSK1x5k3VLSJBJG1mfJYbvR1JkU7xm6/d5J6ASC0OzqJ0mtFjV5IgapHdbN1L3Y7LkGxqIutqwX1F7ZrIubx5pCvyvw5Kb/luByl/5Duh53Oq4GRitYlg7NVHS947yRhBZczwQYItaSfi+spwgIVc9/aEiUwaJgDvLDKOV0tuhuhlkjXiPEpLGYY8ObuxaO457ySam4zYla6lS5G95kJLUprx8IHO6/wKoLhbYpURc6to0hYnXEStFM8IvffwaNkyHHPqDYjjgG2HWDtEKyZ88Xm5+bSn8BBjCRpXVZwGmqI8xCpCdopl2Vo7B72Wk93uHV6pd4Rfg2XDam36wkQl5NvPgnCcTgjH7u+wHbp4zq1MDA9R+d2rk226Ao04oniH2oqQYQYdpiLSgl6L8TZRXRi35QkLAmxhhBW0vYJQnB9Jh143fua7FUeiZVEFcgD9buj1bicVBqYzFmbY8PpbdzsS+hDxKHZKinpV82GCfcaPcZoM5b1gHglUihCHG+z8zE+BhnLFZj3E83klbgyKNnDA3sFbEk4wjK28dvCv21a351TlDZQhbRGZbtzgRlfkkth0N9zcmVujsPIA7ok="
  - secure: "Dk7AoFT8rkX/OHlEzyR+7B438X8B/DlDtWdNEzrTyCbLAKidHP4SnrICRFYXI+WkUNFaQOFEcziJBGoSbZOkrGPcKJgOON/SjZP1nFyU/kAx7NEzoJsINUboG9F+KG1MFDANupmrC6ZPViquL+TPxZuUiyU/nCRRerT/eIUf2lWjSYNkMtpCAtwkjmhO+6FDDAlp+ErdWKu7wRrDyhA72j/sNRCQtld9B2dXJuUY4yXCkGJq1PxX76qI2ZthbOOE1J5DLHQbf5szFdkDeAWWB4hi9xdE7Q6UhyHj4+xuqCtLN1kDS1Eq1b9Tf3iiJld36dMnSvLlHMbtpHLiwl09i6RgTUGUhDdh3Xsp1RENceRtrBXrYwSxXjUgaTcDMIu+oz6Fqlqp1T6Pwauuumfml8Yiris2YIY+ubdswUoVhsS7Jt+vaLsWnVFEH9mTWwEmn8lMCvmzIPJlA8+hC5g4KEjaSxmUho+tdFYj9ZlZ2nkrh0CZO6WtQY79htXlLRX05CnxXA3/AAWwRZh8D7xX06DZxZS/ZoieHD3wEMeCEF2hILdWlKLDJqX5XuGitg0W1aFtMt0++gyEe20Fvbc//EJme7tS+9gCph0xdsTxz1y6xTGiRM1knjQ6Wdc7jA4OQD+Zb2LosTJlApPEHFZB3BFqqBfkYq/Gk7N4rg7mMUI="
deploy:
  provider: releases
  api_key: 
    secure: "aDzcR0vy7GxXp8Lw+1FEvqtNtCyjcRVVhez9p5DPdYtheNnVDRkLXwyxD2+N5MGK/WI7RbIQoInnklAs+WUzbcb9qcjEtsMTS09swD62SqTV80oW/gs0l2SadTguZFG4n6IM8cxZBbQY9jXxnp5WLc3GSFMPnXCwz+XjiN9C2jHbwpS7oNbLoG7S/JdBYNf+DupnY3Bn/NoDCIzQAvJnjp1X9+CkbsBJEn8oU1zmyZ2w4QR94t33Ol9gaehBF9vXn+xn8/FoC+erBX4if3FdXqdPc1p1aPhCx0i3YoCuHJnqY5L57ait3vB93o8lDoA4ZRYECCr0AOA+JSHG556hBZb3pXlG4KZVAixNt9412KqOeGd3QzL/9J31MkLFX5GI6Z7UOqQt2mJWSoupoHwbyCBe711/pM7HU44DHaOEChuo7nlavERYTaG/ncIb0lHNY6dmpGJ9lcj41sp8WV4SqRw55uqnN6PPCoIw7xm9ew1fIMYc0yVRbnnf7s2Ni7nni+iVYQYp3R54mrlFcGhEWPwghqNcdzQfRGMrSeZDO4aeCKOxy0o7/xiQHZYKhubtRCEFql7pmQDPKdEPbXZFNX6sYWvrovLHGqAeY5vczSpZSre0I5nmB0d36Ztao5meD9+RGL+v/jc4pzDlpRRsj/fjCtATW25l2Q4PP3E+JXo="
  file_glob: true
  file: 
    - "target/APIManager_v*.jar"
  skip_cleanup: true
  on:
    tags: true
